// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABgYH5Eipoh52basCPcLIXmTIm2rVYJHg',
    appId: '1:1059292610037:web:1a8c1efdef6760a3dd74bc',
    messagingSenderId: '1059292610037',
    projectId: 'farm-30bee',
    authDomain: 'farm-30bee.firebaseapp.com',
    storageBucket: 'farm-30bee.firebasestorage.app',
    measurementId: 'G-JTLLPLEQV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQLE3csedRFUceB29jM3vnY8gP2xk_fcM',
    appId: '1:1059292610037:android:d541e67de72c620cdd74bc',
    messagingSenderId: '1059292610037',
    projectId: 'farm-30bee',
    storageBucket: 'farm-30bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7i7vuTCYHN2qC-XCCQCdyZrvNMu-lUM',
    appId: '1:1059292610037:ios:3c2728b5d78a80e1dd74bc',
    messagingSenderId: '1059292610037',
    projectId: 'farm-30bee',
    storageBucket: 'farm-30bee.firebasestorage.app',
    androidClientId: '1059292610037-1f10jmv6nraa30dro3qcq3c46hg03893.apps.googleusercontent.com',
    iosClientId: '1059292610037-0funea6use987qgs5d1qqjeuucm6hgn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7i7vuTCYHN2qC-XCCQCdyZrvNMu-lUM',
    appId: '1:1059292610037:ios:3c2728b5d78a80e1dd74bc',
    messagingSenderId: '1059292610037',
    projectId: 'farm-30bee',
    storageBucket: 'farm-30bee.firebasestorage.app',
    androidClientId: '1059292610037-1f10jmv6nraa30dro3qcq3c46hg03893.apps.googleusercontent.com',
    iosClientId: '1059292610037-0funea6use987qgs5d1qqjeuucm6hgn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABgYH5Eipoh52basCPcLIXmTIm2rVYJHg',
    appId: '1:1059292610037:web:21712af00f149a20dd74bc',
    messagingSenderId: '1059292610037',
    projectId: 'farm-30bee',
    authDomain: 'farm-30bee.firebaseapp.com',
    storageBucket: 'farm-30bee.firebasestorage.app',
    measurementId: 'G-D971VVCWMG',
  );
}
